export declare const emailTypes: {
    NODEMAILER: string;
    RESEND: string;
};
export declare const LOGIN_WITH_EMAIL = "/login-with-email";
export declare const LOGIN_WITH_USERNAME = "/login-with-username";
export declare const FORGOT_PASSWORD = "/forgot-password";
export declare const RESET_PASSWORD = "/reset-password";
export declare const REGISTER = "/register";
export declare const LOGOUT = "/logout";
export declare const VERIFY_EMAIL = "/verify-email";
export declare const RESEND_VERIFICATION_EMAIL = "/resend-verification-email";
export declare const REFRESH_TOKEN_ROUTE = "/refresh-token";
export declare const REQUIRED_FIELDS = "All fields are required!";
export declare const USER_NOT_FOUND = "User not found!";
export declare const LOGIN_SUCCESSFUL = "Login successful";
export declare const INVALID_CREDENTIALS = "Invalid credentials";
export declare const INTERNAL_SERVER_ERROR = "Internal Server Error";
export declare const LOGOUT_SUCCESSFUL = "Logout successful";
export declare const UNAUTHORIZED = "Unauthorized";
export declare const USER_REGISTERED_SUCCESSFULLY = "User registered successfully";
export declare const USERNAME_ALREADY_EXISTS = "Username or email already exists";
export declare const PASSWORD_RESET_SUCCESSFUL = "Password reset successful";
